### ISSUE TITLE
Provide nuget package of EF-Adapter 

### ISSUE THREAD

**Issue by ChangeTheCode** [casbin-net/ef-adapter#5]
### Feature request

Provide this ef-adapter as nuget package like [Casbin.NET.Adapter.EFCore](https://www.nuget.org/packages/Casbin.NET.Adapter.EFCore/)

**Comment by hsluoyz** [comment]
@Sagilio plz release it to nuget, thanks!

**Comment by sagilio** [comment]
Already upload: https://www.nuget.org/packages/Casbin.NET.Adapter.EF
Fixed by : [commit: "ci: Add build and release actions"](https://github.com/casbin-net/EF-Adapter/commit/d077fe03ed301039c52061dfc8699d7fa4188740)

**Comment by hsluoyz** [comment]
@Sagilio how to set the logo of the package?

![image](https://user-images.githubusercontent.com/3787410/107368993-2d685280-6b1c-11eb-9470-3568cf786c88.png)

**Comment by sagilio** [comment]
@hsluoyz  It will be pack in the next version package. [chore: Add icon and infomations at nuget package](https://github.com/casbin-net/EF-Adapter/commit/a001f82cde1d957b068c83287c72c2e7dc731944)

**Comment by hsluoyz** [comment]
@Sagilio thanks! We can gradually fix the logos for all packages on Nuget: https://www.nuget.org/packages?q=casbin

**Comment by sagilio** [comment]
> @Sagilio thanks! We can gradually fix the logos for all packages on Nuget: https://www.nuget.org/packages?q=casbin

It is a good idea

**Comment by hsluoyz** [comment]
Issue proposed here: https://github.com/casbin/Casbin.NET/issues/128
